sonar.organization=bason-labs
sonar.projectKey=bason-labs_bs-kara
sonar.sources=bk-web,bk-shared,scripts/acdc
sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,e2e/**
sonar.javascript.lcov.reportPaths=bk-web/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**
